# This is a basic workflow that is manually triggered
name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      param1:
        description: 'First parameter'
        type: boolean
        required: true
        default: 'true'
      param2:
        type: boolean
        description: 'Second parameter'
        required: true 
        default: 'true'
      param3:
        type: boolean
        description: 'third parameter'
        required: true
        default: 'true'
        
env:  
    DOTNET_INSTALL_DIR: "./.dotnet"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: self-hosted
    steps:
    #- name: Set up parameters
    #  run: echo "PARAMS=${{ github.event.inputs.param1 }},${{ github.event.inputs.param2 }},${{ github.event.inputs.param3 }}" >> $GITHUB_ENV

    - name: Set up parameters to list
      run: |
          PARAMS=""
          if [ "${{ github.event.inputs.param1 }}" = "true" ]; then
              PARAMS+="param1x,"
          fi
          if [ "${{ github.event.inputs.param2 }}" = "true" ]; then
              PARAMS+="param2x,"
          fi
          if [ "${{ github.event.inputs.param3 }}" = "true" ]; then
              PARAMS+="param3x,"
          fi
          echo "PARAMS=${PARAMS%?}" >> $GITHUB_ENV      
          
    - name: Working Folder
      run: echo "TDA Dir" && pwd

    - name: Run script to show user inputed params
      run: chmod +rx ./RunScripts/script.sh && ./RunScripts/script.sh 
        
